# Generated by Django 2.2 on 2020-04-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='host',
        ),
    ]
